### ISSUE TITLE
Issue with -win

### ISSUE THREAD

**Issue by SpatiumPrinceps** [paddycup1/Gw2DpsLogUploader#1]
Executing 
`DpsLogUploader.exe -b fotms -past 5h -win -gen ei -embed test [todaysfotms]`
throws 

C:\Users\vm\Desktop>DpsLogUploader.exe -b fotms -past 5h -win -gen ei -embed test [todaysfotms]
Parsing MAMA log C:\Users\vm\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\MAMA\20181013-114034.evtc.zip...
Traceback (most recent call last):
  File "DpsLogUploader.py", line 498, in <module>
  File "DpsLogUploader.py", line 238, in filterLogs
  File "EvtcParser.py", line 201, in __init__
UnboundLocalError: local variable 'filename' referenced before assignment
[3000] Failed to execute script DpsLogUploader

Maybe I'll look into it by myself, bit short on time today

**Comment by SpatiumPrinceps** [comment]
Works fine now! Thank you so much.

Another thing you might want to look in: https://hastebin.com/vavuteguze.xml
It happend with 
.\DpsLogUploader.exe -b fotms -past 1d -win -gen rd ei -embed Todays [fotms]
Tried it again and it didnt happen again, so I guess its might just a case you forgot to catch or something like that. 

Thank you again for this smooth tool :)

**Comment by paddycup1** [comment]
It looks like Gw2Raidar server temporarily crashed...
I've added some error handling, at least it won't abort the whole process.
But it may take much more time to check Raidar result, due to the upload-failed log can never be found on Raidars list.

**Comment by paddycup1** [comment]
I'm so glad that this tool actually helping someone :)
Feel free to report any issue you found!
