### ISSUE TITLE
Normal mode glitching out?!

### ISSUE THREAD

**Issue by SpatiumPrinceps** [paddycup1/Gw2DpsLogUploader#2]
Hello again xD
So today we had the CMs in low level recs. It seems like the uploader tries to upload those although it clearly shouldnt.
I think its stuck now, since raidar rejects those but it keeps trying forever (i can already view the 6 logs in raidar itsself). 
https://hastebin.com/rujidavuge.css
https://i.imgur.com/weOcdGE.png

Also take a look at the ei uploads. I have exactly 6 logs which are applicable to fit the filter, not more and not less. Skorvald for example is 2x in cm (same log twice for some reason....) and 1x in recs

**Comment by paddycup1** [comment]
I must fix the second bug first... because **that is a very silly mistake!!** lol
And the first issue.... Actually, that is expected, because the tool won't check boss id. So if arcdps record the log and put it in the same folder, the tool can't identify them.
I don't want to rely on boss id to recognize which the logs, because one day I may not play GW2 anymore, but I hope the users can update the tool for the new boss by themselves.

But I have an idea for this -- Raidar has an API to retrieve the boss ids it can accept, I can use it to decide which log can upload to Raidar.
The only question is this change need to make a lot of change in codes. So... I will do this, but not now. Maybe at the weekend, I think. :P

**Comment by SpatiumPrinceps** [comment]
Alright, sounds reasonable 👍 
Take your time, dont worry. This tool is amazing, there is no alternative, which comes even close to all the possibilities you are offering. 

Are you interested in a GUI version of it? I think i could develop a frontend which simply generates the command and later feeds that command into your logic. Just let me know, if its worth it in your opinion to put some time on that ^^

**Comment by paddycup1** [comment]
I was planning a GUI version too in the beginning, that will be a good opportunity to learn and practice for me.
But I can't design a nice interface let users quickly pick logs they want in my brain. So I made the command line version, it will be convenient for people who familiar with cmd interface, and keep the possibility to extend it to GUI version
All I want to say is, I'll be glad if someone makes a nice GUI for it. :)

**Comment by SpatiumPrinceps** [comment]
Haha yes, I totally understand you. I dont really like to make guis either. I have a strong dislike for powershell / cmd, prefer zsh on a serious os, but for gaming i have no choice. 

I drafted this up
https://i.imgur.com/7HqyWtf.png

Have no clue about python gui programming too xD I think i could craft something very fast in java, but python no clue what library even to use

**Comment by paddycup1** [comment]
Looking good!

Maybe it can just call my tool through the shell command, no need to use python too?
The config and boss list is json format, so you can access it by the json library.

**Comment by SpatiumPrinceps** [comment]
Yea, I thought about for a while. I wont use python, Javafx seems more appropriate, given the fact I'm quiet familiar with it. 

My client will basically just generate a string and execute your program.

**Comment by paddycup1** [comment]
[Gw2DpsLogUploader.zip](https://github.com/paddycup1/Gw2DpsLogUploader/files/2499166/Gw2DpsLogUploader.zip)
Changed many things XD
I'll push this version after several days test.
As I said, now the tool will try to get Raidar's support list, logs not in the support list will be ignored. Use the command `-NotOnlyRaidar` or `-nord` (I'm looking for better names...) will force upload to Dps.report, but Raidar will still be skipped.
And the shown boss name will be updated according to Raidar's list.

Also, the response message for `-raidarlogin` is added, it will print `get Raidar token success` if successfully get the token.

**Comment by SpatiumPrinceps** [comment]
So, No matter what login you insert, it will always print get raidar token success. 
If i insert some fake passwort, it will overwrite the current raidar token in the config to null and print the success message

**Comment by paddycup1** [comment]
oops, you are right.
Never thought that this action can fail. XD
Now it should print some error message.
[Gw2DpsLogUploader.zip](https://github.com/paddycup1/Gw2DpsLogUploader/files/2499418/Gw2DpsLogUploader.zip)

**Comment by paddycup1** [comment]
Sounds good!

**Comment by paddycup1** [comment]
Guess I can close this now, release 1.1.0 will ignore non-CM fotm encounter by default.
